spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/shiftlane}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:shiftlane}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.properties.hibernate.id.new_generator_mappings=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.web:DEBUG
logging.level.org.hibernate:ERROR
spring.jpa.defer-datasource-initialization=true
spring.mvc.log-request-details=true

#Set RSA keys
rsa.private-key=classpath:certification/private.pem
rsa.public-key=classpath:certification/public.pem
